version: '3.1'
services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
       NGINX_HOST: http://api
       NGINX_PORT: 80
    ports:
      - 80:80
    depends_on:
      - api
    restart: always

  api:
    container_name: app
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:80
    #volumes:
    #  - ./api:/var/www/api
    #  - ./docker/log:/var/log
    restart: always
networks:
  default:
    driver: bridge